import json
from supabase import create_client
import time

# =====================================================
# SUPABASE CONNECTION (UPDATE WITH YOUR CREDENTIALS)
# =====================================================
SUPABASE_URL = "https://fktjmkmzlixlapeyhhyl.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrdGpta216bGl4bGFwZXloaHlsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzE0OTM3MSwiZXhwIjoyMDkyNzI1MzcxfQ.B7ksS7RN-GAz-bQE7oYi_SWVDdyuBkGgKxn_Lhqa3gA"

supabase = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)

print("=" * 60)
print("MEI DRIVE AFRICA - DATA POPULATION SCRIPT")
print("=" * 60)

# =====================================================
# 1. CLEAR EXISTING DATA (Optional - uncomment if needed)
# =====================================================
# print("\n🗑️ Clearing existing data...")
# supabase.table("user_progress").delete().neq("id", 0).execute()
# supabase.table("quiz_attempts").delete().neq("id", 0).execute()
# supabase.table("enrollments").delete().neq("id", 0).execute()
# supabase.table("lessons").delete().neq("id", 0).execute()
# supabase.table("questions").delete().neq("id", 0).execute()
# supabase.table("courses").delete().neq("id", 0).execute()
# print("✅ Existing data cleared")

# =====================================================
# 2. PUSH COURSES
# =====================================================
print("\n📚 PUSHING COURSES...")

courses = [
    {
        "id": 1,
        "name": "Learner Hub",
        "type": "learner",
        "price": 0,
        "duration": "25 hours",
        "lessons": 21,
        "description": "Complete NTSA-approved driver training. Master the rules of the road, vehicle controls, defensive driving, and pass your driving test with confidence.",
        "icon": "fa-id-card",
        "active": True,
        "enrolled": 0
    },
    {
        "id": 2,
        "name": "EV Drivers & Riders",
        "type": "ev",
        "price": 0,
        "duration": "12 hours",
        "lessons": 12,
        "description": "Electric vehicle safety training and operations. Learn about EV technology, charging systems, battery management, and eco-driving techniques.",
        "icon": "fa-charging-station",
        "active": True,
        "enrolled": 0
    },
    {
        "id": 3,
        "name": "Boda Boda Safety",
        "type": "boda",
        "price": 0,
        "duration": "18 hours",
        "lessons": 26,
        "description": "Professional motorcycle rider training. Master defensive riding, passenger safety, protective gear, and road safety for boda boda operators.",
        "icon": "fa-motorcycle",
        "active": True,
        "enrolled": 0
    },
    {
        "id": 4,
        "name": "PSV Professional",
        "type": "psv",
        "price": 2999,
        "duration": "15 hours",
        "lessons": 7,
        "description": "Commercial driver certification for Public Service Vehicles. Learn passenger management, PSV regulations, defensive driving, and professional conduct.",
        "icon": "fa-bus",
        "active": True,
        "enrolled": 0
    },
    {
        "id": 5,
        "name": "School Bus/Van Driver",
        "type": "schoolbus",
        "price": 1999,
        "duration": "12 hours",
        "lessons": 6,
        "description": "School transport safety training. Protect children, master safe loading/unloading, emergency procedures, and child management.",
        "icon": "fa-chalkboard-user",
        "active": True,
        "enrolled": 0
    },
    {
        "id": 6,
        "name": "Advanced Driver Academy",
        "type": "advanced",
        "price": 4999,
        "duration": "20 hours",
        "lessons": 7,
        "description": "Professional driver excellence and fleet management. Master advanced defensive driving, fleet operations, fuel management, and leadership.",
        "icon": "fa-award",
        "active": True,
        "enrolled": 0
    }
]

for course in courses:
    result = supabase.table("courses").upsert(course).execute()
    print(f"  ✅ {course['name']}")

# =====================================================
# 3. PUSH LESSONS/MODULES FOR EACH COURSE
# =====================================================
print("\n📖 PUSHING LESSONS/MODULES...")

# LEARNER HUB LESSONS (21 units)
learner_lessons = [
    {"course_id": 1, "title": "Introduction to Driving", "content": "## Introduction to Driving\n\nMotor vehicles are an important part of our day-to-day living and provide a means for people and goods to be transported from one location to another.\n\nThe goal of driver training is ensure that you, as the driver, are equipped with the right knowledge of how to handle your vehicle and how to act appropriately when using the road.\n\nMost traffic accidents are caused by human error, however this can be easily prevented when the driver is adequately prepared for the traffic situation. This training also ensures that you are prepared with the necessary skills to provide safe and efficient transport services for goods and for passengers.", "order": 1},
    {"course_id": 1, "title": "Fundamental Driving Rules", "content": "## Fundamental Driving Rules\n\nThe road is governed by rules and regulations that ensure order is maintained on the roads at all times. These rules and regulations are derived from international, regional and Kenyan law.\n\n### The Traffic Act\n\nThe Traffic Act sets out the laws that govern the use of roads and the expected conduct of road users. It also includes some of the penalties and fines for road users who do not abide by these laws.\n\n### Highway Code\n\nThe Highway Code is a set of information, advice, guides and mandatory rules for all road users in Kenya. It provides guidelines for animal, pedestrians, cyclists and motorcyclists.\n\n### Key Rules\n\n- Use the horn only when necessary to warn other road users\n- Give right-of-way to police cars, emergency vehicles, and presidential motorcade\n- Never drive in pedestrian-only areas\n- Obey all traffic signs and signals", "order": 2},
    {"course_id": 1, "title": "Model Town & Road Networks", "content": "## Model Town & Road Networks\n\nThe model town board is an example of a road network on a board. It is a simplified representation used to explain the types of roads found in major towns of Kenya and East Africa.\n\n### Road Types\n- **One Way Traffic Road (Dual Carriageway)**: All vehicles move in one direction\n- **Two Way Traffic Road (Single Carriageway)**: Vehicles move in opposite directions\n\n### Roundabout Rules\n- No stopping, no changing lanes, no parking, no overtaking, no waiting\n- Keep left and move in clockwise direction\n- Give way to traffic from the right\n\n### Parking Types\n- **Angle Parking**: Park from farthest end by forward gear, exit by reverse\n- **Flush Parking**: Park from farthest end by reverse, exit by forward driving", "order": 3},
    {"course_id": 1, "title": "Human Factors in Traffic", "content": "## Human Factors in Traffic\n\n### Observation Rules\n- Keep your eyes moving\n- Get a wide view of what is ahead and behind\n- Use all mirrors (rear view and wide view)\n- Pay attention to vehicle instruments\n- Watch for cyclists, motorcyclists and pedestrians\n\n### Fatigue Prevention\n- Get quality sleep before driving\n- Take regular breaks on long journeys\n- Eat balanced meals at regular intervals\n- Keep fit and healthy\n- Avoid driving at night when likely to feel sleepy\n\n### Distractions to Avoid\n- Using hand-held devices (phones)\n- Adjusting radio while driving\n- Grooming, smoking, eating while driving\n- Watching video devices\n\n### Alcohol, Drugs and Medicine\n- Never drink and drive\n- Alcohol slows brain functions, reduces judgment, gives false confidence\n- Do not take medicine that causes drowsiness\n- Legal BAC limit: 0.05% for private drivers, 0.00% for commercial", "order": 4},
    {"course_id": 1, "title": "Vehicle Construction & Controls", "content": "## Vehicle Construction & Controls\n\n### Main Controls\n- **Steering Wheel**: Used to change or maintain direction\n- **Direction Indicator**: Signals turning left or right\n- **Gear Lever**: Used to change gears\n- **Hand Brake**: Keeps vehicle stationary, especially on inclines\n- **Brake Pedal**: Slows speed or stops\n- **Accelerator**: Increases speed\n- **Clutch Pedal**: Used to change gears in manual vehicles\n\n### Dashboard Instruments\n- **Speedometer**: Shows current speed\n- **Temperature Gauge**: Checks engine temperature\n- **Fuel Gauge**: Shows fuel level\n- **Warning Lights**: Alert to issues (oil, battery, brakes)\n\n### Mirrors\n- **Rear-view Mirror**: Flat glass, shows traffic behind\n- **Side Mirrors**: Convex glass, wider field of vision\n\nThe blind spot is the area around the vehicle that the driver cannot directly observe. Always check blind spots before changing lanes.", "order": 5},
    {"course_id": 1, "title": "Self-Inspection of Vehicle", "content": "## Self-Inspection of Vehicle\n\n### Exterior Inspection Checklist\n- **Tyres**: Pressure, tread condition, secure fastening\n- **Reflectors and Lights**: Headlights, turn signals, hazard lights, reverse lights\n- **Mirrors**: Present, properly adjusted, unobstructed\n- **Windshield Wipers**: Work at all settings, wiper fluid available\n- **Windows**: Open and shut without difficulty\n- **Body**: No damage like dents and scratches\n- **Cleanliness**: Windscreen, windows, mirrors clean\n- **Safety Belts**: Functional clasps, clean\n- **Emergency Equipment**: Reflector triangle, fire extinguisher, first aid kit, tools, spare tyre\n- **Paperwork**: Driving licence, insurance, registration\n\n### Interior Inspection\n- Brakes properly adjusted\n- Steering full range of motion\n- Indicators operational\n- Gears shift properly\n- Oil level adequate\n- Coolant level OK\n- Battery terminals clean\n- No fluid leaks", "order": 6},
    {"course_id": 1, "title": "Observation & Mirror Use", "content": "## Observation & Mirror Use\n\n### Driver Visibility\nDriver visibility is the maximum distance at which a driver can clearly identify objects around the car.\n\n### Mirror Checks\n1. Check centre interior mirror first\n2. Check door mirror of direction you're going\n3. Identify potential hazards:\n   - Vehicles driving closely behind\n   - Vehicles approaching quickly\n   - Motorcyclists and cyclists\n\n### The Blind Spot\nAreas around the vehicle the driver cannot directly observe. Check blind spot before:\n- Changing direction when motorcyclists or cyclists are close\n- Overtaking on dual carriageway\n- Changing lanes\n- Any potential hazard may be obscured\n\n### Types of Mirrors\n- **Rear View Mirror**: Flat glass, no distortion, judge speed and distance accurately\n- **Nearside Mirror**: Closest to kerb\n- **Offside Mirror**: Closest to inner lane marker", "order": 7},
    {"course_id": 1, "title": "Vehicle Control", "content": "## Vehicle Control\n\n### Starting the Vehicle\n1. Fully depress clutch pedal for 3 seconds\n2. Put handbrake ON\n3. Turn ignition switch ON\n4. Start motor control\n5. Step lightly on accelerator to warm engine\n6. Check mirrors\n7. Signal\n8. Select appropriate gear\n9. Release handbrake\n10. Let clutch rise until engine speed decreases\n\n### Stopping the Vehicle\n1. Check mirrors\n2. Signal\n3. Remove foot from accelerator\n4. Apply brake gradually\n5. Depress clutch as car comes to rest\n6. Set handbrake ON\n7. Put gear in 1st position\n8. Switch off engine\n\n### Gear Usage\n- **1st Gear**: 0-30 km/h, moving off\n- **2nd Gear**: Slow moving traffic, economical\n- **3rd Gear**: 35-70 km/h\n- **4th Gear**: 60-110 km/h, overtaking\n- **5th Gear**: 80-110 km/h, highway cruising\n\n### Parking at Kerb\n1. Check mirror\n2. Signal\n3. Slow down\n4. Move to suitable distance from kerb\n5. Brake gently, press clutch 5 metres from stop\n6. Apply handbrake, select neutral\n7. Cancel indicator", "order": 8},
    {"course_id": 1, "title": "Communication on the Road", "content": "## Communication on the Road\n\n### MSM Technique (Mirror, Signal, Manoeuvre)\n\nUse before:\n- Moving off\n- Changing direction\n- Overtaking\n- Changing speed\n- Stopping or parking\n\n### Traffic Light Signals\n- **RED**: STOP\n- **RED and AMBER**: STOP, prepare to go\n- **GREEN**: Go if road is clear\n- **AMBER**: STOP at the line\n\n### Hand Signals\n- **Left turn**: Arm out horizontally\n- **Right turn**: Arm out and upward\n- **Slowing down**: Arm out and downward\n\n### Traffic Police Signals\n- **STOP (from behind)**: Hand raised, palm facing drivers\n- **STOP (from front)**: Hand raised, palm facing oncoming traffic\n- **COME ON**: Arm moving in circular motion", "order": 9},
    {"course_id": 1, "title": "Speed Management", "content": "## Speed Management\n\n### Legal Speed Limits in Kenya\n- **50 km/h** – Towns / built-up areas\n- **80 km/h** – Rural roads\n- **100 km/h** – Highways / motorways\n\n### The 4-Second Rule\nTo maintain safe following distance:\n1. When vehicle ahead passes a landmark, count \"one thousand and one...\"\n2. If you pass the landmark before finishing 4 seconds, you're too close\n3. Increase distance\n\n### Stopping Distance\nStopping Distance = Thinking Distance + Braking Distance\n\n**Factors affecting stopping distance:**\n- Speed (higher speed = longer distance)\n- Road conditions (wet/icy increases distance)\n- Vehicle condition (worn tyres, poor brakes)\n- Driver fatigue and distractions\n\n### Braking Techniques\n- **Progressive braking**: Apply brakes gradually\n- **Threshold braking**: Firm pressure just before wheel lock\n- **ABS braking**: Plant and steer, don't pump\n\n**Never freewheel (coast)** – reduces vehicle control and doesn't save fuel.", "order": 10},
    {"course_id": 1, "title": "Space Management", "content": "## Space Management\n\n### Road Conditions\n- **Open Condition**: Clear view, easy to adjust speed and change lanes\n- **Closed Condition**: Limited space, restricted view due to obstructions\n- **Changing Conditions**: Speed limits, road surface, weather, traffic flow changes\n\n### Space Management Techniques\n- Drive at same speed as surrounding traffic\n- Maintain safe following distance (4-second rule)\n- Position vehicle to 'see and be seen'\n\n### Space Recovery\nWhen insufficient space ahead:\n1. Signal intent to slow down\n2. Turn slowly to create more space\n3. Be aware of oncoming vehicle size/weight\n4. Ensure sufficient space before joining a lane\n5. Never reverse to create space (affects vehicles behind)", "order": 11},
    {"course_id": 1, "title": "Emergency Manoeuvres", "content": "## Emergency Manoeuvres\n\n### Brake Failure\n1. Pump brake pedal to restore pressure\n2. Apply parking brake gently while holding release button\n3. Downshift to lower gears\n4. Steer to safety (grass, uphill)\n5. Call for help - do not drive again\n\n### Tyre Blowout\n1. Keep firm grip on steering wheel\n2. Do NOT slam on brakes\n3. Let car slow down gradually\n4. Pull to side of road once slowed\n5. Activate hazard lights\n\n### Wheel Goes Off Pavement\n1. Hold steering firmly\n2. Take foot off accelerator\n3. Avoid heavy braking\n4. When under control, steer back onto pavement\n\n### Headlights Fail\n1. Check switch immediately\n2. If still off, keep left and stop safely\n3. Never drive at night without lights (illegal and dangerous)\n\n### Defensive Driving\nDefensive driving goes beyond basic rules:\n- Anticipate and avoid accidents\n- Provide more protection to yourself and passengers\n- Save lives in dangerous situations\n- Reduce wear and tear on vehicle\n\n**Key techniques:**\n- Improve observation and anticipation\n- Apply sound judgment of speed and distance\n- Never drive when tired", "order": 12},
    {"course_id": 1, "title": "Skid Control & Recovery", "content": "## Skid Control & Recovery\n\n### Causes of Skids\n- Driving faster than road conditions allow\n- Sudden, hard braking\n- Turning too fast\n- Accelerating too quickly\n\n### Types of Skids\n- **Front Wheel Skid**: Vehicle goes off intended course (excess speed entering corner)\n- **Rear Wheel Skid**: Rear swings out (excessive speed with sudden braking)\n\n### Aquaplaning\nOccurs when tyre tread cannot channel away enough water, causing tyres to lose road contact.\n\n**Prevention:**\n- Reduce speed in wet conditions\n- Maintain correct tyre pressure\n- Ensure adequate tread depth\n\n**Recovery:**\n- Ease off accelerator and brakes\n- Let speed drop until tyres regain contact\n\n### Skid Recovery Steps\n1. Take feet off accelerator\n2. Release brake pedal, reapply gently\n3. Quickly turn steering wheel in desired direction\n4. As vehicle corrects, steer opposite direction to stay on path\n5. Continue looking at intended travel path down the road", "order": 13},
    {"course_id": 1, "title": "Adverse Driving Conditions", "content": "## Adverse Driving Conditions\n\n### Night Driving\n- Slow down, especially on unlit roads\n- Don't over-drive headlights\n- Use low beams within 150m of oncoming vehicles\n- Switch to low beams at curves/hilltops\n\n### Fog\n- Slow down gradually\n- Use low beam headlights (high beams reflect off moisture)\n- Use fog lights if available\n- Be patient - avoid overtaking and lane changes\n- If visibility decreases rapidly, pull off road safely\n\n### Rain\n- Reduce speed\n- Increase following distance\n- Avoid sudden braking\n- Stay out of puddles (may hide potholes)\n- First 10 minutes of rain are most dangerous (oil rises)\n\n### Hot Weather\n- Check coolant levels\n- Monitor temperature gauge\n- Avoid driving during hottest hours\n- Stay hydrated\n\n### Poor Visibility\n- Keep windshield and windows clean\n- Use defroster to keep windows clear\n- Clean headlights periodically\n- Use low beams in fog and on dark/overcast days", "order": 14},
    {"course_id": 1, "title": "Preventive Maintenance", "content": "## Preventive Maintenance\n\nPreventive maintenance includes:\n- Vehicle inspection\n- Lubrication\n- Adjustment\n- Cleaning\n- Testing\n- Repair and replacement of worn parts\n\n### Common Issues & Solutions\n\n| Problem | Symptom | Solution |\n|---------|---------|----------|\n| Tyres/Steering | Puncture | Change wheel |\n| Heavy steering | Power steering fault | Seek assistance |\n| Vibrations | Bulge in tyre or wheel imbalance | Change tyre or seek assistance |\n| Brakes | Vehicle pulls to one side | Seek assistance |\n| Brakes | Warning light shows | Check fluid level, seek assistance |\n| Lights | Bulb failure | Check and replace bulb |\n| Engine | Won't start | Check fuel, battery, connections |\n| Engine | Overheating | Check coolant, fan belt |\n\n### Driver's Obligation\nAs owner/driver, regular preventive maintenance:\n- Increases vehicle availability\n- Improves safety\n- Saves repair costs\n- Prevents breakdowns", "order": 15},
    {"course_id": 1, "title": "Conditions of Carriage", "content": "## Conditions of Carriage\n\nConditions of carriage refer to customers' rights and restrictions, and driver's obligations.\n\n### For PSV/Light Vehicles\n- Provide statement of liability\n- State fares/ticketing prices\n- Indicate exceptions with fare prices\n- Abide by code of conduct\n- Address restricted items\n- Provide lost property procedure\n- Display contact details of owner/company\n\n### Commercial Vehicle\nA motor vehicle constructed or adapted for carriage of goods or burdens in connection with any trade, business or agriculture.\n\n### Driver Responsibilities\n- Pick up/drop off at designated points\n- Provide sufficient time for boarding/alighting\n- Assist passengers who need help\n- Address customers respectfully\n- Provide clear information about service and charges\n- Don't carry more passengers or goods than legally allowed", "order": 16},
    {"course_id": 1, "title": "Hazardous Materials", "content": "## Hazardous Materials\n\nHazardous Material is any material prescribed as such by written law, including explosives, petroleum products and any material involving high risk.\n\n### Characteristics\n- **Flammable**: Can burn easily\n- **Corrosive**: Rusts or decomposes\n- **Reactive**: Can explode\n- **Toxic**: Poisonous\n\n### 9 Classes of Hazardous Materials\n1. Explosives\n2. Gases\n3. Flammable Liquids\n4. Flammable Solids\n5. Oxidizing Substances\n6. Toxic & Infectious Substances\n7. Radioactive Material\n8. Corrosives\n9. Miscellaneous Dangerous Goods\n\n### Legal Requirements\n- Special licence required to handle hazardous materials\n- Special equipment and vehicle alterations needed\n- Coordinated by Kenya Bureau of Standards (KBS), NEMA, and NTSA\n\n**DO NOT handle hazardous material without appropriate licensing.**", "order": 17},
    {"course_id": 1, "title": "Emergency Procedures", "content": "## Emergency Procedures\n\n### At Accident Scene\n1. Set reflector triangles 50 metres behind and ahead of vehicle\n2. Call emergency services (999/112)\n3. Move uninjured people to safety\n4. DO NOT move injured unless in immediate danger (fire/explosion)\n5. Do not remove motorcyclist's helmet unless essential\n6. Provide first aid if trained\n7. Stay until police arrive\n\n### First Aid - DR.ABC\n- **Danger**: Make area safe\n- **Response**: Shake gently, talk to casualty\n- **Airway**: Clear throat, tilt head\n- **Breathing**: Check for breath, give artificial respiration if needed\n- **Circulation**: Check pulse, apply CPR if needed\n\n### Bleeding\n1. Apply firm pressure over wound\n2. Use sterile dressing or clean padding\n3. If no broken bones, raise bleeding limb\n4. Tie padding, release pressure every 10 minutes\n\n### Shock\nSigns: cold/pale/damp skin, fast/weak pulse, rapid shallow breathing, nausea\n\nTreatment:\n- Lay person down\n- Loosen tight clothing\n- Keep warm with blanket\n- Talk calmly\n- Raise legs slightly\n\n**NEVER give accident casualty anything to eat or drink.**", "order": 18},
    {"course_id": 1, "title": "Work Planning", "content": "## Work Planning\n\n### Trip Planning\nBefore journey, document:\n- Sender's name, address, phone\n- Pick-up phone number\n- Appointment times\n- Load securing requirements\n- Legal requirements for hazardous goods or cross-border transport\n\n### Factors Affecting Trip Management\n- **Distance**: Longer distance = more preparation, may need co-driver\n- **Time/Traffic**: Peak hours = longer journey\n- **Meals**: Plan stops in advance\n- **Fatigue**: Never start when tired, take breaks\n- **Adverse weather**: Avoid or take precautions\n\n### Time Management\n- Get directions before starting (maps, GPS, other drivers)\n- Know alternative routes\n\n### Legal Limits (Traffic Act Section 66A)\nNo person shall drive a PSV or commercial vehicle for more than **8 hours in any 24-hour period**.\n\n### After Journey\nComplete records of duty, work tickets, or trip cards.", "order": 19},
    {"course_id": 1, "title": "Customer Care", "content": "## Customer Care\n\n### Communication Skills\n- **Patience**: Stay calm in traffic\n- **Attitude**: Positive mindset\n- **Language**: Use respectful language\n\n### Courtesy on the Road\n- Get proper training and licence\n- Apply road safety techniques\n- Take responsibility for actions\n- Be visible - position correctly, signal\n- Keep vehicle clean, number plates visible\n- Ensure passengers comfortable with seatbelts\n\n### Handling Customer Expectations\n- Pick up/drop off at designated points\n- Allow sufficient boarding/alighting time\n- Assist passengers needing help\n- Use respectful language\n- Provide clear service information\n- Provide helmet and reflective jacket for passengers\n- Designate seating for elderly, sickly, expectant mothers\n- Give special consideration to passengers with disabilities\n\n### Personal Hygiene\n- Be smart, sober, clean\n- Keep vehicle clean\n- Number plates visible\n- Safety gear clean\n\n### Sexual Harassment and Discrimination\n- Never make unwelcome sexual requests or comments\n- Never discriminate based on appearance, race, ethnicity, gender, age\n- Create safe environment for vulnerable passengers\n- Report harassment to authorities\n\n### Competitive Riding\n- No more than 2 riders allowed to ride abreast\n- Do not ride at unreasonable speed", "order": 20},
    {"course_id": 1, "title": "The Examination", "content": "## The Examination\n\n### Preparing for NTSA Driving Test\n\n**Before the Test:**\n- Go to examination centre on time\n- Bring all required documents\n- Ensure vehicle is roadworthy and clean\n- Get adequate rest the night before\n- Eat a light meal\n\n**During the Test:**\n- Stay calm and confident\n- Demonstrate all mirror checks visibly\n- Use MSM routine consistently\n- Obey all traffic signs and signals\n- Maintain appropriate speed\n- Show defensive driving techniques\n\n**Common Failure Mistakes:**\n- Not checking mirrors and blind spots\n- Speeding\n- Stalling on hill start\n- Incorrect lane use at roundabouts\n- Not stopping completely at STOP signs\n- Poor observation at junctions\n- Incorrect parking\n- Not using indicators properly\n\n**After the Test:**\n- Listen carefully to examiner feedback\n- If passed, complete licence application\n- If failed, note areas for improvement and retest\n\n### 1000+ Quiz Bank\nPractice with our comprehensive question bank covering:\n- Road Signs\n- Highway Code\n- Defensive Driving\n- Traffic Rules\n- Parking & Stopping\n- Roundabouts & Junctions\n- Vehicle Inspection\n- Emergency Handling\n- First Aid\n- Night Driving\n- Weather & Hazard Driving\n- Motorcycle/Boda Safety\n- PSV & Passenger Safety\n- Eco Driving\n- Professional Conduct", "order": 21}
]

for lesson in learner_lessons:
    supabase.table("lessons").upsert(lesson).execute()
    print(f"  ✅ Learner Hub: {lesson['title']}")

# BODA BODA SAFETY LESSONS (26 modules)
boda_lessons = [
    {"course_id": 3, "title": "Introduction to Boda Boda Safety", "content": "## Introduction to Boda Boda Safety\n\n### What is a Boda Boda?\nA boda boda is a motorcycle used for passenger transport, parcel delivery, and commercial transport services.\n\n### Importance of Road Safety\nRoad safety protects riders, passengers, pedestrians, and other road users. Safe riding prevents injuries, deaths, property damage, and financial losses.\n\n### Qualities of a Professional Rider\n- Disciplined\n- Respects traffic laws\n- Maintains cleanliness\n- Honest and respectful\n- Rides responsibly", "order": 1},
    {"course_id": 3, "title": "Motorcycle Parts & Controls", "content": "## Motorcycle Parts & Controls\n\n### Main Controls\n- Throttle\n- Front brake\n- Rear brake\n- Clutch\n- Gear lever\n- Ignition switch\n- Indicators\n- Horn\n\n### Understanding Motorcycle Parts\n- Engine\n- Tyres\n- Suspension\n- Mirrors\n- Chain\n- Battery\n- Lights\n\nUnderstanding motorcycle parts helps detect problems early, improve safety, and reduce breakdowns.", "order": 2},
    {"course_id": 3, "title": "Personal Protective Equipment (PPE)", "content": "## Personal Protective Equipment (PPE)\n\n### Essential Safety Gear\n\n**Helmet**\n- Protects head during accidents\n- Wear approved helmets only\n- Fasten chin straps properly\n- Replace damaged helmets\n\n**Reflective Jacket**\n- Improves visibility during night riding, rain, and foggy weather\n\n**Gloves**\n- Protect hands and fingers\n- Improve grip control\n\n**Boots**\n- Protect feet, ankles, and lower legs\n- Sturdy construction required", "order": 3},
    {"course_id": 3, "title": "Pre-Ride Inspection", "content": "## Pre-Ride Inspection\n\n### Daily Inspection Checklist\n\n**Tyres:**\n- Check tyre pressure\n- Inspect tyre condition\n- Look for punctures\n\n**Brakes:**\n- Front brake operation\n- Rear brake operation\n- Brake fluid level\n\n**Lights:**\n- Headlights\n- Brake lights\n- Indicators\n\n**Other Checks:**\n- Mirrors properly adjusted\n- Horn works\n- Fuel level adequate\n- Chain tension correct\n\n### Importance of Inspection\n- Prevents accidents\n- Detects faults early\n- Improves motorcycle performance", "order": 4},
    {"course_id": 3, "title": "Starting & Moving Safely", "content": "## Starting & Moving Safely\n\n### Before Starting\n1. Wear all safety gear\n2. Ensure motorcycle is in neutral\n3. Check surroundings\n4. Start engine carefully\n\n### Moving Off Safely\n1. Check mirrors\n2. Signal properly\n3. Observe traffic\n4. Move smoothly\n\n### Stopping Safely\n- Brake gradually\n- Use both brakes\n- Avoid sudden stops", "order": 5},
    {"course_id": 3, "title": "Defensive Riding Techniques", "content": "## Defensive Riding Techniques\n\n### What is Defensive Riding?\nDefensive riding means anticipating danger, staying alert, avoiding risky behavior, and protecting yourself and passengers.\n\n### Defensive Riding Skills\n\n**Observation:**\n- Constantly observe vehicles, pedestrians, animals, and road conditions\n\n**Following Distance:**\n- Maintain safe distance to react quickly, brake safely, and avoid collisions\n\n**Mirror Use:**\n- Use mirrors regularly to monitor traffic and prepare for lane changes\n\n**Hazard Awareness:**\n- Watch for potholes, oil spills, sudden stops, and reckless drivers", "order": 6},
    {"course_id": 3, "title": "Road Signs & Traffic Rules", "content": "## Road Signs & Traffic Rules\n\n### Types of Road Signs\n\n**Regulatory Signs:**\n- STOP signs\n- No entry\n- Speed limits\n\n**Warning Signs:**\n- Curves ahead\n- Slippery road\n- School zone\n\n**Informative Signs:**\n- Directions\n- Hospitals\n- Petrol stations\n\n### Traffic Rules for Riders\n- Obey traffic lights\n- Follow speed limits\n- Respect pedestrians\n- Use indicators properly", "order": 7},
    {"course_id": 3, "title": "Lane Discipline & Positioning", "content": "## Lane Discipline & Positioning\n\n### Safe Lane Positioning\nCorrect lane position improves visibility, improves safety, and reduces collisions.\n\n### Dangerous Riding to Avoid\n- NEVER weave through traffic dangerously\n- NEVER ride between large vehicles\n- NEVER ride on pedestrian walkways\n\n### Blind Spot Awareness\nAvoid staying in blind spots of:\n- Trucks\n- Buses\n- Cars\n\nAlways assume drivers cannot see you when in their blind spots.", "order": 8},
    {"course_id": 3, "title": "Safe Braking Techniques", "content": "## Safe Braking Techniques\n\n### Proper Braking\nUse both front and rear brakes together for:\n- Better balance\n- Faster stopping\n- Reduced skidding\n\n### Emergency Braking\n1. Stay calm\n2. Keep motorcycle upright\n3. Apply brakes progressively\n4. Avoid locking wheels\n\n### Dangers of Sudden Braking\n- Skidding\n- Passenger falls\n- Loss of control", "order": 9},
    {"course_id": 3, "title": "Cornering & Turning", "content": "## Cornering & Turning\n\n### Safe Turning\n**Before turning:**\n- Reduce speed\n- Check mirrors\n- Signal early\n\n**During turning:**\n- Lean smoothly\n- Maintain balance\n- Avoid sudden acceleration\n\n### Roundabout Safety\n- Give way appropriately\n- Maintain lane discipline\n- Watch for vehicles entering\n- Never stop, change lanes, or overtake on roundabout", "order": 10},
    {"course_id": 3, "title": "Overtaking Safely", "content": "## Overtaking Safely\n\n### Safe Overtaking Steps\n1. Check mirrors\n2. Signal\n3. Confirm road is clear\n4. Accelerate safely\n5. Return smoothly\n\n### Never Overtake:\n- On corners\n- Near junctions\n- On pedestrian crossings\n- In heavy traffic\n- When solid yellow line is present", "order": 11},
    {"course_id": 3, "title": "Riding in Traffic", "content": "## Riding in Traffic\n\n### Urban Riding Safety\nWatch for:\n- Sudden stops\n- Opening car doors\n- Pedestrians\n- Matatus changing lanes\n- Buses pulling over\n\n### Traffic Discipline\n- Stay patient\n- Avoid aggressive riding\n- Respect all road users\n- Don't weave between lanes\n\n### Filtering Safely\n- Only when traffic is stopped or very slow\n- Do not exceed 15-20 km/h when filtering\n- Watch for gaps where cars may change lanes", "order": 12},
    {"course_id": 3, "title": "Riding at Night", "content": "## Riding at Night\n\n### Night Riding Risks\n- Reduced visibility\n- Slower reaction time\n- Harder for others to see you\n\n### Night Riding Safety\n**Use:**\n- Headlights properly (low beam in town, high beam on dark roads)\n- Reflective jackets\n- Reduced speed (10-15 km/h slower)\n\n**Avoid:**\n- Dark unsafe roads\n- Speeding at night\n- Wearing dark clothing", "order": 13},
    {"course_id": 3, "title": "Riding During Rain & Bad Weather", "content": "## Riding During Rain & Bad Weather\n\n### Rain Riding Tips\n- Reduce speed significantly\n- Increase following distance (4+ seconds)\n- Brake gently and early\n- Avoid slippery surfaces\n\n### Dangerous Surfaces\n- Oil spills (very slippery when wet)\n- Mud patches\n- Flooded roads\n- Painted road markings (slippery when wet)\n- Metal grates and manhole covers\n\n### Hydroplaning Prevention\n- Maintain proper tyre pressure\n- Ensure adequate tread depth\n- Reduce speed in standing water", "order": 14},
    {"course_id": 3, "title": "Passenger (Pillion) Safety", "content": "## Passenger (Pillion) Safety\n\n### Passenger Responsibilities\n- Wear helmet properly fastened\n- Sit properly on designated seat\n- Avoid sudden movement\n- Hold rider or grab handles safely\n- Keep feet on footrests\n\n### Rider Responsibilities\n- Ensure passenger has helmet\n- Explain safety instructions before moving\n- Ride smoothly (no sudden acceleration/braking)\n- Avoid overloading\n- Ensure passenger is comfortable before moving", "order": 15},
    {"course_id": 3, "title": "Know Your Passenger", "content": "## Know Your Passenger\n\n### Passenger Categories\n\n**Children:**\n- Extra care needed\n- Lower speed\n- Proper helmets required\n- Never carry more than one child\n\n**Elderly Passengers:**\n- Assistance boarding/alighting\n- Smooth riding\n- Lower speed\n\n**Pregnant Women:**\n- Slow, careful riding\n- Avoid bumps\n- Only on smooth roads\n- Limit distance\n\n### Passenger Communication\nBefore moving:\n- Explain safety instructions\n- Confirm destination\n- Agree on fare\n- Ensure comfort", "order": 16},
    {"course_id": 3, "title": "Personal Hygiene & Professional Conduct", "content": "## Personal Hygiene & Professional Conduct\n\n### Importance of Hygiene\n- Builds customer confidence\n- Prevents disease spread\n- Creates professionalism\n\n### Hygiene Practices\n- Bathe daily\n- Wear clean clothes\n- Clean helmet regularly\n- Wash hands frequently\n- Keep motorcycle clean\n\n### Professional Conduct\n- Respect passengers\n- Avoid abusive language\n- Be honest about fares\n- Maintain discipline\n- Report incidents properly", "order": 17},
    {"course_id": 3, "title": "Motorcycle Maintenance Basics", "content": "## Motorcycle Maintenance Basics\n\n### Basic Maintenance Checks\n\n**Regular Checks (Daily):**\n- Oil level\n- Tyre pressure\n- Brake operation\n- Lights and indicators\n\n**Weekly Checks:**\n- Chain tension and lubrication\n- Battery terminals\n- Suspension condition\n\n**Monthly Checks:**\n- Spark plug condition\n- Air filter cleaning\n- Full bolt tightening check\n\n### Importance of Maintenance\n- Prevents breakdowns\n- Improves safety\n- Saves repair costs\n- Extends motorcycle life", "order": 18},
    {"course_id": 3, "title": "Fuel & Lubrication Safety", "content": "## Fuel & Lubrication Safety\n\n### Fuel Safety\n**NEVER:**\n- Smoke near fuel\n- Overfill tank (allow expansion space)\n- Spill fuel (clean immediately)\n- Store fuel in inappropriate containers\n\n**DO:**\n- Turn off engine when refueling\n- Use correct fuel grade\n- Check for leaks regularly\n\n### Lubrication\nLubricate regularly:\n- Chain (every 500 km)\n- Cables (throttle, clutch, brake)\n- Pivot points\n\nProper lubrication reduces wear, improves performance, and extends component life.", "order": 19},
    {"course_id": 3, "title": "Emergency Handling & First Aid", "content": "## Emergency Handling & First Aid\n\n### Accident Response\n1. Stop safely\n2. Protect passengers (move to safety)\n3. Call emergency services (999/112)\n4. Give first aid if trained\n5. Do not move seriously injured unless immediate danger\n6. Stay at scene until police arrive\n\n### First Aid Basics\n- Control bleeding with direct pressure\n- Keep victim calm and warm\n- Avoid unnecessary movement\n- Check for breathing and pulse\n\n### Emergency Contacts\n- Police/Fire/Ambulance: 999 or 112\n- NTSA Hotline: 1195\n- Red Cross: 1199", "order": 20},
    {"course_id": 3, "title": "Common Causes of Accidents", "content": "## Common Causes of Accidents\n\n### Main Causes\n- Overspeeding\n- Drunk riding\n- Poor road conditions\n- Reckless overtaking\n- Fatigue\n- Phone use while riding\n- Not wearing helmet\n- Overloading\n- Riding without lights at night\n\n### Accident Prevention\n- Stay alert at all times\n- Ride responsibly\n- Follow traffic laws\n- Wear full protective gear\n- Maintain safe following distance\n- Never drink and ride\n- Get adequate rest\n- Keep motorcycle well-maintained", "order": 21},
    {"course_id": 3, "title": "Alcohol, Drugs & Fatigue", "content": "## Alcohol, Drugs & Fatigue\n\n### Dangers of Alcohol\n- Slows reaction time\n- Reduces judgment\n- Causes accidents\n- Legal limit for boda boda: 0.00%\n- Penalties: fine 10,000 KES or jail\n\n### Fatigue\nFatigue causes:\n- Poor concentration\n- Slow reactions\n- Sleepiness\n- Microsleep (dangerous!)\n\n### Safety Tips\n- Rest properly before riding\n- Take breaks every 2 hours on long trips\n- Avoid riding while tired\n- Never ride under influence of alcohol or drugs\n- Some medications cause drowsiness - check labels", "order": 22},
    {"course_id": 3, "title": "Customer Care & Communication", "content": "## Customer Care & Communication\n\n### Good Customer Service\n- Be polite and respectful\n- Speak clearly and professionally\n- Help passengers safely\n- Explain safety rules before moving\n\n### Communication Skills\nCommunicate clearly about:\n- Destination\n- Fare (agree before departure)\n- Safety instructions\n- Estimated time of arrival\n\n### Handling Disputes\n- Stay calm\n- Don't argue aggressively\n- Suggest fair resolution\n- Involve stage manager if needed\n- Never use violence", "order": 23},
    {"course_id": 3, "title": "Digital Safety & Mobile Phone Use", "content": "## Digital Safety & Mobile Phone Use\n\n### Mobile Phone Dangers\n**NEVER:**\n- Text while riding\n- Watch videos while riding\n- Use phone without stopping safely\n- Take calls without hands-free (illegal)\n\n### Safe Digital Practices\nUse phones only:\n- When parked safely\n- For emergency communication\n- Before starting journey (set GPS)\n\n### M-Pesa Safety\n- Check transaction confirmation before passenger leaves\n- Be aware of fake M-Pesa messages\n- Keep phone secure at all times\n- Report suspicious transactions immediately", "order": 24},
    {"course_id": 3, "title": "Environmental Responsibility", "content": "## Environmental Responsibility\n\n### Environmental Care for Riders\n- Avoid fuel spills\n- Maintain motorcycle properly to reduce smoke emissions\n- Dispose of waste oil properly (not in drains)\n- Don't litter - use dustbins\n- Reduce noise pollution (no modified exhausts)\n- Avoid riding on pavements (protects pedestrians)\n\n### Benefits of Environmental Care\n- Cleaner environment\n- Better public health\n- Reduced pollution\n- Better community relations\n- Longer engine life", "order": 25},
    {"course_id": 3, "title": "Final Safety Guidelines", "content": "## Final Safety Guidelines\n\n### Final Rider Rules\n\n**ALWAYS:**\n- Wear protective gear (helmet, reflective jacket, gloves, boots)\n- Obey traffic laws\n- Respect passengers\n- Ride responsibly\n- Maintain motorcycle properly\n\n**NEVER:**\n- Drink and ride\n- Speed excessively\n- Carry more than one passenger\n- Ride without helmet\n- Use phone while riding\n\n### Professional Rider's Pledge\n\"I pledge to ride safely, protect my passengers, respect other road users, maintain my motorcycle properly, and represent the boda boda profession with honor and integrity.\"\n\n**\"Safe riding protects lives, passengers, property, and the future of every professional boda boda rider.\"**", "order": 26}
]

for lesson in boda_lessons:
    supabase.table("lessons").upsert(lesson).execute()
    print(f"  ✅ Boda Boda: {lesson['title']}")

# PSV PROFESSIONAL LESSONS (7 modules)
psv_lessons = [
    {"course_id": 4, "title": "Introduction to PSV Operations", "content": "## Introduction to PSV Operations\n\n### What is a PSV?\nA Public Service Vehicle (PSV) is a vehicle used to transport passengers or goods for commercial purposes. Examples include matatus, buses, taxis, and vans.\n\n### Role of a PSV Driver\nA professional PSV driver must:\n- Ensure passenger safety\n- Obey traffic laws\n- Maintain discipline\n- Provide customer service\n- Represent their SACCO professionally", "order": 1},
    {"course_id": 4, "title": "PSV Rules & Regulations", "content": "## PSV Rules & Regulations\n\n### Important PSV Requirements\nDrivers must:\n- Hold valid driving licenses\n- Carry PSV badges displayed visibly\n- Follow NTSA regulations\n- Ensure vehicle inspection compliance\n- Have speed limiter functional (max 80 km/h)\n- Belong to registered SACCO\n\n### Passenger Safety Rules\n- Board safely from designated stages\n- Wear seat belts where available\n- Avoid distracting drivers\n- No standing while vehicle is moving\n- Use designated exits\n\n### Penalties for Violations\n- Overloading: vehicle impoundment + fine\n- No PSV badge: fine up to 20,000 KES\n- Speeding: fine and possible licence suspension", "order": 2},
    {"course_id": 4, "title": "Defensive Driving for PSV", "content": "## Defensive Driving for PSV\n\n### Defensive Driving Skills\nDrivers should:\n- Anticipate danger before it happens\n- Maintain safe following distance (4+ seconds due to weight)\n- Avoid speeding (max 80 km/h)\n- Observe mirrors frequently (every 5-8 seconds)\n\n### Hazard Awareness\nWatch for:\n- Pedestrians (especially near markets and stages)\n- Motorcycles weaving through traffic\n- Sudden stops by vehicles ahead\n- Reckless drivers overtaking dangerously\n\n### Special PSV Considerations\n- Extra weight = longer stopping distance\n- Brake earlier and more gently\n- Watch for passengers standing before moving\n- Use engine brake on downhill slopes", "order": 3},
    {"course_id": 4, "title": "Passenger Management", "content": "## Passenger Management\n\n### Customer Care\nProfessional drivers should:\n- Treat passengers respectfully\n- Avoid abusive language\n- Communicate clearly about fares and route\n- Help with luggage\n- Announce stops clearly\n\n### Handling Difficult Passengers\nDrivers should:\n- Stay calm (never argue aggressively)\n- Avoid confrontation\n- Seek assistance from conductor or stage manager\n- Involve police if necessary\n- Never use violence\n\n### Passenger Loading Rules\n- Board from designated stages only\n- Do not move until passengers are seated\n- Wait for boarding/alighting to complete\n- No overloading (fine: KES 10,000+ vehicle impoundment)", "order": 4},
    {"course_id": 4, "title": "Vehicle Inspection & Maintenance", "content": "## Vehicle Inspection & Maintenance\n\n### Daily Inspection Checklist\n**Check:**\n- Tyres (pressure, tread, condition)\n- Brakes (operation, fluid level)\n- Lights (headlights, brake lights, indicators)\n- Horn\n- Mirrors (clean, properly adjusted)\n- Engine oil level\n- Coolant level\n- Windscreen and wipers\n\n### Importance of Maintenance\nProper maintenance:\n- Prevents breakdowns (reduces passenger complaints)\n- Improves safety (prevents accidents)\n- Reduces operating costs\n- Extends vehicle life\n- Maintains SACCO reputation\n\n### Weekly Inspection Requirements\n- Full brake inspection\n- Suspension check\n- Electrical system check\n- PSV badge inspection by NTSA", "order": 5},
    {"course_id": 4, "title": "Emergency Response for PSV", "content": "## Emergency Response for PSV\n\n### Emergency Handling Steps\n1. Stop safely (hazard lights on)\n2. Protect passengers (evacuate if necessary)\n3. Call emergency services (999/112)\n4. Provide first aid if trained\n5. Report to SACCO and police\n\n### Fire Safety\nDrivers should:\n- Know fire extinguisher use (PASS: Pull, Aim, Squeeze, Sweep)\n- Evacuate passengers safely and quickly\n- Avoid panic (calm passengers)\n- Have emergency exits accessible\n\n### Accident Reporting\n1. Do not move vehicle (if safe)\n2. Take photos of damage\n3. Collect witness information\n4. Report to SACCO within 24 hours\n5. Complete police abstract\n6. Notify insurance company", "order": 6},
    {"course_id": 4, "title": "Professional Conduct", "content": "## Professional Conduct\n\n### Professional Behavior\nDrivers should:\n- Maintain cleanliness (vehicle and personal)\n- Dress professionally (uniform where required)\n- Avoid alcohol and drugs\n- Respect all road users\n- Be punctual (respect passenger time)\n\n### Driver Ethics\n- No stage fighting (queue discipline)\n- No overcharging passengers\n- No racing (competition with other PSVs)\n- No phone use while driving\n- Report incidents honestly\n\n### Code of Conduct\n1. Be courteous to passengers\n2. Maintain speed limit\n3. Keep to designated route\n4. Display PSV badge clearly\n5. Keep vehicle roadworthy\n\n**\"Professional PSV drivers protect lives through discipline, responsibility, and safe driving.\"**", "order": 7}
]

for lesson in psv_lessons:
    supabase.table("lessons").upsert(lesson).execute()
    print(f"  ✅ PSV Professional: {lesson['title']}")

# SCHOOL BUS LESSONS (6 modules)
schoolbus_lessons = [
    {"course_id": 5, "title": "Introduction to School Transport Safety", "content": "## Introduction to School Transport Safety\n\n### Importance of School Transport Safety\nSchool transport safety protects:\n- Children (most vulnerable road users)\n- Drivers\n- Parents\n- Other road users\n\n### Why Children Need Extra Care\n- They may panic easily in emergencies\n- They may not understand road dangers\n- They have unpredictable behavior\n- Smaller size makes them harder to see\n- They may run into traffic suddenly\n\n### Driver's Special Responsibility\nSchool bus drivers are responsible for the most precious cargo - children. Every decision must prioritize child safety.", "order": 1},
    {"course_id": 5, "title": "Child Safety Management", "content": "## Child Safety Management\n\n### Boarding & Alighting Safety\nDrivers should:\n- Stop completely at designated zones\n- Ensure children cross safely (use stop arm where available)\n- Never move until all children are seated\n- Count children before and after each trip\n- Check for sleeping children after trip\n\n### Supervision of Children\nDrivers should:\n- Monitor discipline (calmly, without aggression)\n- Prevent overcrowding (no standing)\n- Ensure seat belt use where available\n- Assign seats to maintain order\n- Have a system for attendance tracking\n\n### Loading/Unloading Protocol\n1. Pull over safely with hazard lights\n2. Let children off one at a time\n3. Wait for children to reach sidewalk before moving\n4. Look for children running back to vehicle\n5. Never reverse into children", "order": 2},
    {"course_id": 5, "title": "Safe Driving Practices", "content": "## Safe Driving Practices\n\n### Safe Driving Rules\nDrivers should:\n- Reduce speed near schools (30 km/h in school zones)\n- Obey all school zone signs\n- Avoid all distractions (no phone, no eating)\n- Never leave children unattended in vehicle\n\n### Defensive Driving\nWatch for:\n- Children crossing suddenly between parked cars\n- School traffic congestion\n- Parents parking carelessly\n- Other drivers ignoring stop signs\n- Children running after dropped items\n\n### Specific School Bus Techniques\n- Use lower gear on hills (better control)\n- Extra following distance (children can be unpredictable)\n- Check mirrors frequently (children may be outside vehicle)\n- Use crossing arm/gate if available\n- Flash lights to warn approaching drivers", "order": 3},
    {"course_id": 5, "title": "Vehicle Safety & Inspection", "content": "## Vehicle Safety & Inspection\n\n### Daily School Vehicle Inspection\n**Check:**\n- Brakes (in good condition)\n- Tyres (proper pressure and tread)\n- Emergency exits (functional)\n- Seat condition (secure and intact)\n- Seat belts (all working)\n- Stop arm/sign (if equipped, must work)\n- First aid kit (stocked)\n- Fire extinguisher (charged)\n\n### Cleanliness & Hygiene\nSchool vehicles should:\n- Be cleaned daily (inside and out)\n- Have proper ventilation\n- Maintain hygiene standards (sanitize after each trip)\n- No food debris (prevents pests, allergies)\n\n### Vehicle Markings\n- \"SCHOOL BUS\" clearly displayed\n- Emergency contact numbers visible\n- Maximum capacity posted", "order": 4},
    {"course_id": 5, "title": "Emergency Response", "content": "## Emergency Response\n\n### Child Emergency Procedures\nIn emergencies:\n1. Keep children calm (panic makes situation worse)\n2. Evacuate safely (emergency exits)\n3. Count children after evacuation\n4. Contact school authorities immediately\n5. Call emergency services (999/112)\n6. Do not leave children unattended\n\n### First Aid Awareness\nDrivers should know:\n- Basic first aid (CPR, choking, bleeding)\n- Emergency contacts (school, parents, ambulance)\n- Child protection procedures (reporting injuries)\n- Allergy emergency response (EpiPen where applicable)\n\n### Fire Evacuation\n1. Stop immediately\n2. Turn off engine\n3. Open all exits\n4. Evacuate children in calm, orderly manner\n5. Move children away from vehicle (50 metres)\n6. Call emergency services\n7. Never go back into burning vehicle", "order": 5},
    {"course_id": 5, "title": "Professional Conduct", "content": "## Professional Conduct\n\n### Child Protection\nDrivers should:\n- Respect children (never physical discipline)\n- Avoid abusive language\n- Maintain professionalism at all times\n- Report suspected abuse to school/police\n- Never be alone with a child after hours\n\n### Communication with Parents\nDrivers should:\n- Report incidents promptly (accidents, behavior issues)\n- Communicate delays professionally\n- Be respectful even with difficult parents\n- Document all concerns\n\n### Driver's Pledge\n- I will put child safety above all else\n- I will drive defensively and obey all traffic laws\n- I will maintain my vehicle properly\n- I will be patient and kind with children\n- I will represent my school/company with professionalism\n\n**\"Safe school transport protects children, builds trust, and supports education.\"**", "order": 6}
]

for lesson in schoolbus_lessons:
    supabase.table("lessons").upsert(lesson).execute()
    print(f"  ✅ School Bus: {lesson['title']}")

# ADVANCED DRIVER ACADEMY LESSONS (7 modules)
advanced_lessons = [
    {"course_id": 6, "title": "Professional Driver Excellence", "content": "## Professional Driver Excellence\n\n### Qualities of an Advanced Driver\nProfessional drivers should:\n- Demonstrate discipline at all times\n- Maintain punctuality (respect client time)\n- Practice defensive driving consistently\n- Show leadership to junior drivers\n\n### Driver Ethics\nDrivers should:\n- Respect confidentiality (client information)\n- Protect passengers and cargo\n- Avoid corruption (bribes, illegal payments)\n- Maintain integrity in all dealings\n\n### Corporate Representation\n- Vehicle cleanliness reflects company\n- Professional appearance matters\n- Customer service is part of safety\n- Company reputation depends on drivers", "order": 1},
    {"course_id": 6, "title": "Advanced Defensive Driving", "content": "## Advanced Defensive Driving\n\n### Advanced Driving Skills\nDrivers should:\n- Anticipate hazards early (scan 20 seconds ahead)\n- Maintain escape routes at all times\n- Adjust to weather conditions proactively\n- Use commentary driving technique\n\n### Highway Driving\nSafe highway driving requires:\n- Proper overtaking technique\n- Speed management (don't exceed limits)\n- Fatigue control (stop every 2 hours)\n- Safe following distance (4 seconds)\n\n### IPSGA System\n- **Information**: Gather using mirrors and observation\n- **Position**: Take correct lane position\n- **Speed**: Adjust speed for conditions\n- **Gear**: Select appropriate gear\n- **Acceleration**: Smoothly accelerate\n\n### Emergency Handling at Speed\n- Brake failure: downshift, use handbrake gradually\n- Tyre blowout: firm grip, no sudden brakes\n- Skid recovery: steer into skid, no brakes", "order": 2},
    {"course_id": 6, "title": "Fleet Management Basics", "content": "## Fleet Management Basics\n\n### What is Fleet Management?\nFleet management involves:\n- Managing company vehicles\n- Monitoring driver performance\n- Controlling fuel usage\n- Vehicle maintenance planning\n- Compliance with regulations\n\n### Fleet Responsibilities\nFleet managers should:\n- Schedule maintenance proactively\n- Monitor driver performance data\n- Ensure legal compliance (licences, insurance)\n- Track fuel consumption\n- Manage accidents and claims\n\n### Driver Performance Metrics\n- Fuel efficiency (km per litre)\n- On-time performance\n- Accident-free records\n- Customer satisfaction\n- Vehicle condition reports", "order": 3},
    {"course_id": 6, "title": "Fuel Management", "content": "## Fuel Management\n\n### Fuel Saving Techniques\nDrivers should:\n- Avoid harsh acceleration (smooth driving)\n- Reduce idling (turn off engine when waiting)\n- Maintain proper tyre pressure\n- Use cruise control on highways\n- Anticipate traffic to avoid braking\n- Remove unnecessary weight\n\n### Preventing Fuel Theft\nFleet operators should:\n- Monitor fuel records (track usage vs distance)\n- Use tracking systems to detect anomalies\n- Conduct surprise inspections\n- Install anti-siphon devices\n- Review fuel receipts against odometer\n\n### Fuel Efficiency Targets\n- Target 15+ km/litre for diesel vehicles\n- Target 12+ km/litre for petrol vehicles\n- Track and reward efficient drivers\n- Investigate outliers (low efficiency = problem)", "order": 4},
    {"course_id": 6, "title": "Accident Management", "content": "## Accident Management\n\n### Accident Reporting Procedure\nDrivers should:\n1. Stop immediately (do not leave scene)\n2. Report to police within 24 hours\n3. Record details (time, location, conditions)\n4. Take photos if safe to do so\n5. Contact fleet supervisor immediately\n6. Obtain witness information\n7. Complete company accident report form\n\n### Insurance Awareness\nDrivers should understand:\n- Insurance procedures (claim process)\n- Documentation requirements (police abstract)\n- Excess amounts (what driver/company pays)\n- Coverage limits (what is and isn't covered)\n\n### Accident Investigation\n- Root cause analysis\n- Driver training needs identified\n- Preventative measures implemented\n- Fleet safety review after serious accidents", "order": 5},
    {"course_id": 6, "title": "Vehicle Tracking & Digital Systems", "content": "## Vehicle Tracking & Digital Systems\n\n### Modern Fleet Technology\nFleet systems include:\n- GPS tracking (real-time location)\n- Fuel monitoring (consumption tracking)\n- Driver behavior monitoring (speeding, harsh braking)\n- Route planning and optimization\n- Electronic logging devices (duty hours)\n\n### Benefits of Tracking Systems\nTracking systems help:\n- Improve security (recovery if stolen)\n- Reduce fuel theft (detect anomalies)\n- Improve efficiency (reduce idle time)\n- Verify driver hours (prevent fatigue)\n- Customer updates (accurate ETAs)\n- Insurance premiums (reduce with telematics)\n\n### Data-Driven Fleet Management\n- Use data to coach drivers\n- Identify high-risk drivers for training\n- Optimize routes for fuel efficiency\n- Schedule maintenance based on usage, not calendar", "order": 6},
    {"course_id": 6, "title": "Leadership & Professionalism", "content": "## Leadership & Professionalism\n\n### Leadership Skills\nProfessional drivers should:\n- Mentor junior drivers (share knowledge)\n- Promote safety culture (lead by example)\n- Demonstrate responsibility (own mistakes)\n- Represent company professionally\n\n### Workplace Discipline\nDrivers should:\n- Respect company policies\n- Maintain time management\n- Avoid misconduct (drugs, alcohol, theft)\n- Report issues to management\n\n### Continuous Improvement\n- Attend refresher training annually\n- Stay updated on traffic laws\n- Learn from accidents (prevent recurrence)\n- Seek feedback from passengers/management\n\n### Fleet Safety Culture\n- Safety meetings (monthly)\n- Recognition for safe driving (awards)\n- Driver of the month programs\n- Zero-tolerance for substance abuse\n\n**\"Advanced professional drivers combine safety, discipline, technology, leadership, and responsibility to achieve transport excellence.\"**", "order": 7}
]

for lesson in advanced_lessons:
    supabase.table("lessons").upsert(lesson).execute()
    print(f"  ✅ Advanced Academy: {lesson['title']}")

# EV DRIVER LESSONS (12 modules from the EV document)
ev_lessons = [
    {"course_id": 2, "title": "Understanding EV Charging Systems", "content": "## Understanding EV Charging Systems\n\n### What is an EV Charging System?\nAn EV charging system transfers electrical energy from a power source to the vehicle battery.\n\n### Main Charging Components\n- **Charging Port**: Keep clean and dry, close cover after use\n- **Charging Cable**: Avoid twisting or dragging on rough surfaces\n- **Battery Management System (BMS)** : Controls charging, prevents overheating, monitors voltage\n- **Charging Station**: Home charging, public charging, fast charging stations, battery swap stations\n\n### Charging Safety\n- Never use damaged cables\n- Keep charging area dry\n- Turn vehicle off before charging", "order": 1},
    {"course_id": 2, "title": "Types of EV Charging", "content": "## Types of EV Charging\n\n### Slow Charging (Level 1/2 AC)\n- Lower power, longer charging time (4-10 hours)\n- Safer for overnight charging\n- Best for home use, fleet parking\n\n### Fast Charging (Level 3 DC)\n- Charges quickly (30-60 minutes to 80%)\n- Higher voltage\n- Use for commercial operations and long trips\n- Monitor temperature during fast charging\n- Avoid frequent unnecessary fast charging (degrades battery)\n\n### Battery Swapping\n- Popular for electric boda bodas\n- Saves time, reduces downtime\n- Convenient for commercial riders", "order": 2},
    {"course_id": 2, "title": "Safe Charging Procedures", "content": "## Safe Charging Procedures\n\n### Before Charging Checklist\n✔ Check charging cable for damage\n✔ Inspect connector pins for debris\n✔ Ensure charging area is dry\n✔ Verify charging station condition\n✔ Turn vehicle off before charging\n\n### During Charging Rules\n- Do not tamper with cables\n- Avoid using damaged sockets\n- Keep away from water\n- Monitor charging indicators\n\n### After Charging Procedure\n1. Stop charging correctly (use app or button)\n2. Disconnect cable safely (don't yank)\n3. Replace charging cover\n4. Store cable properly (coil without kinking)\n\n### Safety Hazards to Avoid\n- Wet charging environments\n- Damaged wires\n- Overloaded sockets\n- Unauthorized chargers\n- Exposed connectors", "order": 3},
    {"course_id": 2, "title": "EV Driving Skills", "content": "## EV Driving Skills\n\n### Basic EV Driving Skills\n\n**Smooth Acceleration:**\n- EVs respond very quickly (instant torque)\n- Accelerate gradually to avoid jerky movement\n- Avoid sudden power application\n\n**Steering Control:**\n- Use both hands\n- Maintain lane position\n- Avoid sudden swerving\n\n**Speed Management:**\n- Observe speed limits\n- Reduce speed in crowded areas\n- Maintain safe following distance\n\n### Regenerative Braking\nRegenerative braking:\n- Slows the vehicle when you lift off accelerator\n- Recharges battery during braking\n- Improves energy efficiency by 10-25%\n\n**Driver Tips:**\n- Release accelerator early when approaching stops\n- Anticipate stops to maximize regen\n- Avoid harsh braking (wastes energy)\n- Practice one-pedal driving if available", "order": 4},
    {"course_id": 2, "title": "Electric Motorcycle Riding Skills", "content": "## Electric Motorcycle Riding Skills\n\n### Rider Positioning\nCorrect posture improves:\n- Balance\n- Visibility\n- Comfort\n- Control\n\n**Proper Riding Position:**\n- Keep both hands on handlebars\n- Keep feet on footrests\n- Sit upright\n- Keep eyes ahead\n\n### Cornering Skills\n- Slow down before turning\n- Lean gently (EVs have different weight distribution)\n- Accelerate smoothly after turn\n\n### Braking Skills\n- Apply brakes gradually\n- Use both brakes together\n- Use regenerative braking for normal stops\n- Avoid panic braking\n\n### Riding in Traffic\n- Watch blind spots (EVs are quiet - pedestrians may not hear you)\n- Anticipate pedestrian movement\n- Avoid aggressive riding\n- Keep safe distance", "order": 5},
    {"course_id": 2, "title": "Night Driving & Riding for EVs", "content": "## Night Driving & Riding for EVs\n\n### Visibility Safety\nDrivers and riders must:\n- Use headlights properly (low beam in town, high beam on dark roads)\n- Wear reflective gear\n- Reduce speed at night (10-15 km/h slower)\n- Keep windshields and visors clean\n\n### Common Night Hazards\n- Poor visibility (especially on unlit roads)\n- Pedestrians without reflective clothing\n- Animals crossing roads\n- Unmarked vehicles without lights\n- EV silence means pedestrians may not hear you coming\n\n### EV-Specific Night Tips\n- Ensure headlights are LED (many EVs have bright LEDs)\n- Don't blind oncoming traffic with high beams\n- Use fog lights in poor conditions\n- Keep charging port area clean to avoid debris in dark", "order": 6},
    {"course_id": 2, "title": "Wet Weather EV Operations", "content": "## Wet Weather EV Operations\n\n### Safety Guidelines\n\n**During Rain:**\n- Reduce speed (wet roads = longer stopping distance)\n- Increase following distance (4+ seconds)\n- Avoid sudden braking\n- Avoid flooded roads\n\n### Hydroplaning Prevention\nHydroplaning occurs when tyres lose road contact due to water.\n\n**Prevention:**\n- Maintain proper tyre pressure\n- Ensure adequate tread depth\n- Reduce speed in standing water\n- Avoid sudden steering or braking\n\n**If hydroplaning:**\n- Don't brake suddenly\n- Ease off accelerator\n- Steer straight until tyres regain contact\n\n### EV-Specific Wet Weather Notes\n- EVs are well-sealed, safe in rain\n- Avoid deep puddles (may damage underbody connectors)\n- Regenerative braking reduces skid risk\n- After flood exposure, have battery inspected", "order": 7},
    {"course_id": 2, "title": "Passenger & Customer Safety in EVs", "content": "## Passenger & Customer Safety in EVs\n\n### Passenger Protection\nDrivers and riders should:\n- Ensure passengers wear seat belts/helmets\n- Assist passengers safely\n- Avoid reckless riding/driving\n- Maintain clean vehicles\n\n### EV-Specific Passenger Considerations\n- EV acceleration is instant - can cause motion sickness\n- Accelerate smoothly for passenger comfort\n- Explain regenerative braking to passengers\n- Use Eco mode when carrying passengers\n\n### Customer Service for EV Taxi/Ride-hailing\n- Explain EV features to curious passengers\n- Be prepared for questions about range\n- Offer to pre-condition cabin temperature\n- Ensure charging port is secure before passenger boarding", "order": 8},
    {"course_id": 2, "title": "Daily Vehicle Inspection for EVs", "content": "## Daily Vehicle Inspection for EVs\n\n### Pre-Operation Inspection Checklist\n\n**Check:**\n- Battery level (plan charging before 20%)\n- Tyre condition and pressure\n- Brake operation (including regen feel)\n- Lights and indicators (LEDs can fail without warning)\n- Charging cables (no damage, clean)\n- Mirrors (clean, properly adjusted)\n- Horn (works)\n- Warning lights on dashboard\n\n### EV-Specific Checks\n- Check for battery warning lights\n- Listen for unusual sounds from electric motor\n- Check charging port for debris or damage\n- Verify regen feels normal\n- Check coolant level (battery cooling system)\n\n### Weekly Checks\n- Tyre rotation (EV torque wears tyres faster)\n- Brake pad inspection (EVs use brakes less)\n- Software update check\n- Undercarriage inspection for damage", "order": 9},
    {"course_id": 2, "title": "Emergency Response for EVs", "content": "## Emergency Response for EVs\n\n### Battery Emergency Signs\n🚨 **Stop immediately if you notice:**\n- Smoke from battery area\n- Burning smell (sweet or chemical odor)\n- Excessive heat from battery\n- Dashboard battery warning light\n- Rapid range loss (20%+ sudden drop)\n\n### Emergency Procedures\n\n**In Case of Battery Fire:**\n1. Stop safely\n2. Evacuate passengers immediately\n3. Keep 15+ metre distance\n4. Call emergency services (999/112)\n5. DO NOT attempt to extinguish with dry chemical - water or foam only\n6. Warn others to stay away\n\n### Accident Response\n1. Turn off vehicle\n2. Secure accident scene\n3. Avoid exposed orange cables (high voltage)\n4. Assume battery may be damaged\n5. Don't park in garage after accident (could ignite hours later)\n6. Wait for trained responders\n\n### Emergency Contacts\n- Police/Fire/Ambulance: 999 or 112\n- EV roadside assistance: [your provider]\n- EV manufacturer emergency line", "order": 10},
    {"course_id": 2, "title": "EV Maintenance", "content": "## EV Maintenance\n\n### EV vs Petrol Maintenance Comparison\n\n| Service | Petrol | EV |\n|---------|--------|-----|\n| Oil changes | Every 5,000-10,000 km | ❌ Not needed |\n| Air filter | Every 15,000 km | ❌ Not needed |\n| Spark plugs | Every 30,000 km | ❌ Not needed |\n| Brake pads | 30,000-60,000 km | 100,000+ km |\n| Coolant | Every 50,000 km | Every 80,000 km |\n\n### EV Maintenance Schedule\n\n**Every 5,000 km (DIY):**\n- Check tyre pressure\n- Inspect tyres for wear\n- Clean charging port\n- Check windshield washer fluid\n\n**Every 15,000 km (Professional):**\n- Tyre rotation\n- Brake inspection and cleaning\n- Cabin air filter replacement\n- Battery health check\n- Coolant level check\n- Software updates\n\n**Every 80,000 km (Professional):**\n- Battery coolant replacement\n- Full vehicle inspection\n- High voltage system check", "order": 11},
    {"course_id": 2, "title": "Final EV Driver Responsibilities", "content": "## Final EV Driver Responsibilities\n\n### Every EV Operator Should:\n- Drive responsibly (smooth acceleration, anticipate stops)\n- Protect passengers (safe loading/unloading)\n- Follow road rules (speed limits, signals)\n- Maintain vehicle safety (regular inspections)\n- Use charging systems properly (avoid frequent 100% charges)\n- Respect pedestrians and other road users\n\n### Environmental Benefits\n- Zero tailpipe emissions\n- Lower carbon footprint\n- Reduced noise pollution\n- Less dependence on imported fuel\n\n### Professional Pride\nAs an EV driver/rider, you are part of Kenya's green mobility revolution. Your safe, professional operation helps build confidence in electric vehicles.\n\n**\"Safe charging, disciplined driving, and responsible riding are the foundations of successful electric mobility operations.\"**\n\n### Quick Reference: EV Daily Checklist\n- [ ] Check battery level (20-80% for daily)\n- [ ] Check tyre pressure\n- [ ] Clean charging port\n- [ ] Check for warning lights\n- [ ] Plan charging stops for long trips", "order": 12}
]

for lesson in ev_lessons:
    supabase.table("lessons").upsert(lesson).execute()
    print(f"  ✅ EV Course: {lesson['title']}")

# =====================================================
# 4. PUSH QUIZ QUESTIONS (1000+ from quiz bank)
# =====================================================
print("\n📝 PUSHING QUIZ QUESTIONS...")

quiz_questions = [
    # Road Signs Category
    {"category": "Road Signs", "question_text": "What does a STOP sign mean?", "option_a": "Slow down only", "option_b": "Continue carefully", "option_c": "Come to a complete stop", "option_d": "Overtake carefully", "correct_option": "c", "explanation": "A STOP sign means you must come to a complete stop, check both directions, and only proceed when safe."},
    {"category": "Road Signs", "question_text": "A triangular road sign normally indicates:", "option_a": "Direction", "option_b": "Warning", "option_c": "Parking", "option_d": "Speed limit", "correct_option": "b", "explanation": "Triangular signs are warning signs that alert drivers to potential dangers ahead."},
    {"category": "Road Signs", "question_text": "A red circular sign usually means:", "option_a": "Information", "option_b": "Restriction or prohibition", "option_c": "Tourist attraction", "option_d": "Road condition", "correct_option": "b", "explanation": "Red circular signs indicate restrictions or prohibitions (e.g., no entry, speed limit)."},
    {"category": "Road Signs", "question_text": "What does a double continuous yellow line mean?", "option_a": "Parking allowed", "option_b": "Overtaking allowed", "option_c": "No overtaking", "option_d": "Bus stop", "correct_option": "c", "explanation": "A double continuous yellow line means no overtaking is allowed."},
    {"category": "Road Signs", "question_text": "What shape is a STOP sign?", "option_a": "Circle", "option_b": "Triangle", "option_c": "Octagon", "option_d": "Rectangle", "correct_option": "c", "explanation": "STOP signs are octagonal (eight-sided) with a red background and white letters."},
    {"category": "Road Signs", "question_text": "A yellow diamond-shaped sign indicates:", "option_a": "Warning", "option_b": "Regulatory", "option_c": "Information", "option_d": "Stop", "correct_option": "a", "explanation": "Yellow diamond signs are warning signs indicating potential hazards ahead."},
    {"category": "Road Signs", "question_text": "What does a blue circle with a white arrow mean?", "option_a": "One-way street", "option_b": "Roundabout ahead", "option_c": "Mini-roundabout", "option_d": "No entry", "correct_option": "a", "explanation": "A blue circle with a white arrow indicates the direction of a one-way street."},
    {"category": "Road Signs", "question_text": "What does a circular blue sign with a red diagonal line mean?", "option_a": "No entry", "option_b": "No parking", "option_c": "No stopping", "option_d": "Speed limit", "correct_option": "a", "explanation": "A red circle with a diagonal line through it indicates no entry."},
    {"category": "Road Signs", "question_text": "What does a green traffic light mean?", "option_a": "Stop", "option_b": "Prepare to stop", "option_c": "Go if safe", "option_d": "Slow down", "correct_option": "c", "explanation": "Green means you may proceed if the intersection is clear."},
    {"category": "Road Signs", "question_text": "What does an amber traffic light mean?", "option_a": "Speed up", "option_b": "Stop at the line", "option_c": "Continue normally", "option_d": "Park", "correct_option": "b", "explanation": "Amber means stop at the line unless it would be unsafe to do so."},
    
    # Highway Code
    {"category": "Highway Code", "question_text": "Why is the Highway Code important?", "option_a": "For entertainment", "option_b": "To improve road safety", "option_c": "To increase speed", "option_d": "To reduce fuel only", "correct_option": "b", "explanation": "The Highway Code promotes safety, responsible behavior and courtesy for all road users."},
    {"category": "Highway Code", "question_text": "Before changing lanes you should:", "option_a": "Accelerate immediately", "option_b": "Check mirrors and blind spots", "option_c": "Ignore other vehicles", "option_d": "Stop suddenly", "correct_option": "b", "explanation": "Always check mirrors and blind spots before changing lanes to ensure it's safe."},
    {"category": "Highway Code", "question_text": "Seat belts are important because they:", "option_a": "Improve music quality", "option_b": "Prevent accidents", "option_c": "Reduce injury during accidents", "option_d": "Increase speed", "correct_option": "c", "explanation": "Seat belts reduce injury by keeping occupants in place during a crash."},
    {"category": "Highway Code", "question_text": "You may only use your car horn when:", "option_a": "Stopped in traffic", "option_b": "Parked at the roadside", "option_c": "Your vehicle is moving and need to warn others", "option_d": "At any time", "correct_option": "c", "explanation": "The horn should only be used to warn other road users of your presence while moving."},
    {"category": "Highway Code", "question_text": "You must give right-of-way to:", "option_a": "Any vehicle behind you", "option_b": "Police cars and emergency vehicles with sirens", "option_c": "Bicycles only", "option_d": "No one", "correct_option": "b", "explanation": "Police cars, fire engines, and ambulances with flashing lights/sirens have right-of-way."},
    
    # Defensive Driving
    {"category": "Defensive Driving", "question_text": "Defensive driving means:", "option_a": "Aggressive driving", "option_b": "Anticipating and avoiding danger", "option_c": "Driving fast", "option_d": "Ignoring traffic rules", "correct_option": "b", "explanation": "Defensive driving means anticipating hazards and taking action to avoid accidents."},
    {"category": "Defensive Driving", "question_text": "A safe following distance helps you:", "option_a": "Race other vehicles", "option_b": "Reduce fuel only", "option_c": "React safely to danger", "option_d": "Block other drivers", "correct_option": "c", "explanation": "A safe following distance gives you time to react to hazards ahead."},
    {"category": "Defensive Driving", "question_text": "When driving in rain you should:", "option_a": "Increase speed", "option_b": "Brake harshly", "option_c": "Reduce speed and increase distance", "option_d": "Ignore visibility", "correct_option": "c", "explanation": "Rain reduces traction - reduce speed and increase following distance."},
    {"category": "Defensive Driving", "question_text": "What is the recommended following distance in normal conditions?", "option_a": "1 second", "option_b": "2 seconds", "option_c": "3 seconds", "option_d": "4 seconds", "correct_option": "b", "explanation": "The two-second rule is standard for dry conditions."},
    {"category": "Defensive Driving", "question_text": "What does \"cover brake\" mean?", "option_a": "Resting foot on brake pedal", "option_b": "Applying full brake", "option_c": "Using handbrake", "option_d": "Releasing brake", "correct_option": "a", "explanation": "Covering the brake reduces reaction time by 0.5 seconds."},
    
    # Traffic Rules
    {"category": "Traffic Rules", "question_text": "Driving under the influence of alcohol is:", "option_a": "Safe at low speed", "option_b": "Acceptable at night", "option_c": "Dangerous and illegal", "option_d": "Recommended", "correct_option": "c", "explanation": "Drunk driving is dangerous and illegal - legal limit is 0.05% for private drivers."},
    {"category": "Traffic Rules", "question_text": "Using a phone while driving may cause:", "option_a": "Better concentration", "option_b": "Distraction and accidents", "option_c": "Better balance", "option_d": "Faster reaction", "correct_option": "b", "explanation": "Phone use distracts drivers and significantly increases accident risk."},
    {"category": "Traffic Rules", "question_text": "At a red traffic light you must:", "option_a": "Continue carefully", "option_b": "Stop completely", "option_c": "Overtake", "option_d": "Reverse", "correct_option": "b", "explanation": "Red means STOP completely - proceed only when light turns green."},
    {"category": "Traffic Rules", "question_text": "What is the legal blood alcohol limit for a private driver in Kenya?", "option_a": "0.00%", "option_b": "0.05%", "option_c": "0.08%", "option_d": "0.10%", "correct_option": "b", "explanation": "Kenya's legal BAC limit is 0.05% for private drivers (0.00% for commercial)."},
    {"category": "Traffic Rules", "question_text": "What is the minimum age for a learner's driving licence in Kenya?", "option_a": "16 years", "option_b": "17 years", "option_c": "18 years", "option_d": "21 years", "correct_option": "c", "explanation": "You must be 18 years old to apply for a learner's driving licence."},
    
    # Boda Boda Safety
    {"category": "Boda Safety", "question_text": "What is the legal requirement for boda boda riders regarding helmets?", "option_a": "Only rider needs helmet", "option_b": "Only passenger needs helmet", "option_c": "Both rider and passenger must wear helmets", "option_d": "No helmet required", "correct_option": "c", "explanation": "Both rider and passenger must wear approved helmets."},
    {"category": "Boda Safety", "question_text": "What is the alcohol limit for a boda boda rider?", "option_a": "0.05%", "option_b": "0.02%", "option_c": "0.00%", "option_d": "0.08%", "correct_option": "c", "explanation": "Commercial riders have zero tolerance - 0.00% BAC limit."},
    {"category": "Boda Safety", "question_text": "What reflective gear is required for boda boda riders at night?", "option_a": "Reflective vest", "option_b": "Reflective helmet", "option_c": "Reflective gloves", "option_d": "Reflective boots", "correct_option": "a", "explanation": "A reflective vest is mandatory for night riding to improve visibility."},
    {"category": "Boda Safety", "question_text": "How often should a boda boda rider check tyre pressure?", "option_a": "Daily", "option_b": "Weekly", "option_c": "Monthly", "option_d": "Yearly", "correct_option": "a", "explanation": "Tyres should be checked daily for safety and fuel efficiency."},
    
    # PSV Safety
    {"category": "PSV Safety", "question_text": "What is the maximum speed limit for PSV vehicles in Kenya?", "option_a": "60 km/h", "option_b": "70 km/h", "option_c": "80 km/h", "option_d": "90 km/h", "correct_option": "c", "explanation": "PSV vehicles are limited to 80 km/h by speed governors."},
    {"category": "PSV Safety", "question_text": "What document must a PSV driver display visibly?", "option_a": "Driving licence", "option_b": "PSV badge", "option_c": "Insurance certificate", "option_d": "Logbook", "correct_option": "b", "explanation": "A valid PSV badge must be displayed on the vehicle."},
    {"category": "PSV Safety", "question_text": "How often should a PSV vehicle undergo inspection?", "option_a": "Monthly", "option_b": "Weekly", "option_c": "Daily", "option_d": "Yearly", "correct_option": "b", "explanation": "PSV vehicles require weekly inspection by NTSA-approved centers."},
    
    # EV Driving
    {"category": "EV Driving", "question_text": "What does regen stand for in electric vehicles?", "option_a": "Regeneration braking", "option_b": "Regular engine", "option_c": "Reverse gear", "option_d": "Rear engine", "correct_option": "a", "explanation": "Regenerative braking recovers energy when slowing down and charges the battery."},
    {"category": "EV Driving", "question_text": "Which charging type is fastest for EVs?", "option_a": "Level 1 AC", "option_b": "Level 2 AC", "option_c": "DC Fast Charging", "option_d": "Standard outlet", "correct_option": "c", "explanation": "DC Fast Charging can charge up to 80% in 30-60 minutes."},
    {"category": "EV Driving", "question_text": "What is the best practice for EV battery longevity?", "option_a": "Always charge to 100%", "option_b": "Keep between 20% and 80%", "option_c": "Fully discharge weekly", "option_d": "Use only fast charging", "correct_option": "b", "explanation": "Avoiding extreme charge levels (0% or 100%) reduces battery degradation."},
    {"category": "EV Driving", "question_text": "What should you never cut in an EV?", "option_a": "Brake lines", "option_b": "Orange high-voltage cables", "option_c": "Coolant hoses", "option_d": "Tyres", "correct_option": "b", "explanation": "Orange cables carry high voltage and can cause severe injury or death."},
    
    # Emergency Handling
    {"category": "Emergency", "question_text": "If your brakes fail you should:", "option_a": "Panic", "option_b": "Stay calm and slow down safely", "option_c": "Jump out immediately", "option_d": "Close your eyes", "correct_option": "b", "explanation": "Stay calm, pump brakes, downshift, and use handbrake gradually."},
    {"category": "Emergency", "question_text": "In case of an accident you should first:", "option_a": "Run away", "option_b": "Ensure safety and seek help", "option_c": "Ignore injured people", "option_d": "Continue driving", "correct_option": "b", "explanation": "First ensure scene safety, then call for help and assist injured."},
    {"category": "Emergency", "question_text": "What does the 'A' in DR.ABC first aid stand for?", "option_a": "Alert", "option_b": "Airway", "option_c": "Accident", "option_d": "Aid", "correct_option": "b", "explanation": "A = Airway - ensure the casualty's airway is clear."},
    
    # First Aid
    {"category": "First Aid", "question_text": "First aid is important because it:", "option_a": "Replaces hospitals", "option_b": "Provides immediate assistance", "option_c": "Causes accidents", "option_d": "Delays treatment", "correct_option": "b", "explanation": "First aid provides immediate care before professional help arrives."},
    {"category": "First Aid", "question_text": "A bleeding victim should:", "option_a": "Be ignored", "option_b": "Receive pressure on the wound", "option_c": "Run around", "option_d": "Drink alcohol", "correct_option": "b", "explanation": "Apply direct pressure to control bleeding."},
    
    # Weather Driving
    {"category": "Weather", "question_text": "During fog you should:", "option_a": "Increase speed", "option_b": "Use proper lights and reduce speed", "option_c": "Ignore visibility", "option_d": "Overtake continuously", "correct_option": "b", "explanation": "Use low beams or fog lights, reduce speed, and increase following distance."},
    {"category": "Weather", "question_text": "Wet roads increase:", "option_a": "Tyre grip only", "option_b": "Skidding risk", "option_c": "Visibility", "option_d": "Fuel quality", "correct_option": "b", "explanation": "Wet roads reduce traction, increasing the risk of skidding."}
]

# Insert questions in batches
batch_size = 10
for i in range(0, len(quiz_questions), batch_size):
    batch = quiz_questions[i:i+batch_size]
    for q in batch:
        supabase.table("questions").upsert(q).execute()
    print(f"  ✅ Inserted questions {i+1} to {min(i+batch_size, len(quiz_questions))}")

# =====================================================
# 5. PUSH LIBRARY RESOURCES
# =====================================================
print("\n📚 PUSHING LIBRARY RESOURCES...")

library_resources = [
    {"title": "Kenya Highway Code", "description": "Official NTSA highway code handbook for all road users", "category": "PDF", "content_url": "#", "tags": ["highway code", "official"], "downloads": 0},
    {"title": "Defensive Driving Guide", "description": "Complete defensive driving techniques for Kenyan roads", "category": "PDF", "content_url": "#", "tags": ["defensive", "safety"], "downloads": 0},
    {"title": "Boda Boda Safety Handbook", "description": "Professional rider safety guide", "category": "PDF", "content_url": "#", "tags": ["boda", "motorcycle"], "downloads": 0},
    {"title": "EV Safety Manual", "description": "Electric vehicle safety, charging, and maintenance guide", "category": "PDF", "content_url": "#", "tags": ["ev", "electric"], "downloads": 0},
    {"title": "First Aid for Road Accidents", "description": "What to do before help arrives", "category": "Article", "content_text": "DR.ABC: Danger, Response, Airway, Breathing, Circulation\n\nControl bleeding with direct pressure\nKeep victim warm and calm\nNever move seriously injured unless immediate danger", "tags": ["first aid", "emergency"], "downloads": 0},
    {"title": "PSV Driver Code of Conduct", "description": "Professional standards for PSV operators", "category": "PDF", "content_url": "#", "tags": ["psv", "professionalism"], "downloads": 0},
    {"title": "Night Riding Safety Tips", "description": "Stay visible and safe after dark", "category": "Tip", "content_text": "- Wear reflective vest at all times\n- Use both headlight beams appropriately\n- Reduce speed by 15 km/h\n- Stay away from parked cars\n- Avoid overtaking on bends", "tags": ["night safety", "tips"], "downloads": 0},
    {"title": "School Transport Safety Guide", "description": "Protocols for school bus drivers", "category": "Article", "content_text": "1. Always count children before moving\n2. Use stop arm when loading/unloading\n3. Ensure children are seated\n4. Never leave child unattended\n5. Check for sleeping children after trip", "tags": ["school bus", "child safety"], "downloads": 0}
]

for resource in library_resources:
    supabase.table("library_resources").upsert(resource).execute()
    print(f"  ✅ {resource['title']}")

print("\n" + "=" * 60)
print("🎉 DATA POPULATION COMPLETE!")
print("=" * 60)
print(f"\n📊 SUMMARY:")
print(f"  • 6 Courses added")
print(f"  • 21 Learner Hub modules")
print(f"  • 26 Boda Boda modules")
print(f"  • 7 PSV modules")
print(f"  • 6 School Bus modules")
print(f"  • 7 Advanced Academy modules")
print(f"  • 12 EV modules")
print(f"  • {len(quiz_questions)} Quiz questions (add more from the quiz bank document)")
print(f"  • {len(library_resources)} Library resources")
print("\n✅ All data successfully pushed to Supabase!")
